Joose={top:this,stub:function(){return function(){throw Error("Modules can not be instantiated");}},VERSION:3.018,AUTHORITY:"jsan:NPLATONOV"};
Joose.A={each:function(a,b,c){for(var c=c||this,d=0,e=a.length;d<e;d++)if(b.call(c,a[d],d)===!1)return!1},eachR:function(a,b,c){for(var c=c||this,d=a.length-1;d>=0;d--)if(b.call(c,a[d],d)===!1)return!1},exists:function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]==b)return!0;return!1},map:function(a,b,c){for(var c=c||this,d=[],e=0,f=a.length;e<f;e++)d.push(b.call(c,a[e],e));return d},grep:function(a,b){var c=[];Joose.A.each(a,function(a){b(a)&&c.push(a)});return c},remove:function(a,b){var c=[];Joose.A.each(a,
function(a){a!==b&&c.push(a)});return c}};Joose.S={saneSplit:function(a,b){var c=(a||"").split(b);c.length==1&&!c[0]&&c.shift();return c},uppercaseFirst:function(a){return a.substr(0,1).toUpperCase()+a.substr(1,a.length-1)},strToClass:function(a,b){var c=b||Joose.top;Joose.A.each(a.split("."),function(a){if(c)c=c[a];else return!1});return c}};
Joose.O={each:function(a,b,c){var c=c||this,d;for(d in a)if(b.call(c,a[d],d)===!1)return!1;if(Joose.is_IE)return Joose.A.each(["toString","constructor","hasOwnProperty"],function(d){if(a.hasOwnProperty(d))return b.call(c,a[d],d)})},eachOwn:function(a,b,c){c=c||this;return Joose.O.each(a,function(d,e){if(a.hasOwnProperty(e))return b.call(c,d,e)},c)},copy:function(a,b){b=b||{};Joose.O.each(a,function(a,d){b[d]=a});return b},copyOwn:function(a,b){b=b||{};Joose.O.eachOwn(a,function(a,d){b[d]=a});return b},
getMutableCopy:function(a){var b=function(){};b.prototype=a;return new b},extend:function(a,b){return Joose.O.copy(b,a)},isEmpty:function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},isInstance:function(a){return a&&a.meta&&a.constructor==a.meta.c},wantArray:function(a){if(a instanceof Array)return a;return[a]},isFunction:function(a){return typeof a=="function"&&a.constructor!=/ /.constructor}};
Joose.I={Array:function(){return[]},Object:function(){return{}},Function:function(){return arguments.callee},Now:function(){return new Date}};Joose.C=typeof JOOSE_CFG!="undefined"?JOOSE_CFG:{};Joose.is_IE=!1;Joose.is_NodeJS=Boolean(typeof process!="undefined"&&process.pid);Joose.Proto=Joose.stub();Joose.Proto.Empty=Joose.stub();Joose.Proto.Empty.meta={};
(function(){Joose.Proto.Object=Joose.stub();var a=function(){var c=a.caller;if(c==b)c=c.caller;if(!c.SUPER)throw"Invalid call to SUPER";return c.SUPER[c.methodName].apply(this,arguments)},b=function(a){return this.SUPER.apply(this,a)};Joose.Proto.Object.prototype={SUPERARG:b,SUPER:a,INNER:function(){throw"Invalid call to INNER";},BUILD:function(a){return arguments.length==1&&typeof a=="object"&&a||{}},initialize:function(){},toString:function(){return"a "+this.meta.name}};Joose.Proto.Object.meta=
{constructor:Joose.Proto.Object,methods:Joose.O.copy(Joose.Proto.Object.prototype),attributes:{}};Joose.Proto.Object.prototype.meta=Joose.Proto.Object.meta})();
(function(){Joose.Proto.Class=function(){return this.initialize(this.BUILD.apply(this,arguments))||this};var a={VERSION:null,AUTHORITY:null,constructor:Joose.Proto.Class,superClass:null,name:null,attributes:null,methods:null,meta:null,c:null,defaultSuperClass:Joose.Proto.Object,BUILD:function(a,c){this.name=a;return{__extend__:c||{}}},initialize:function(a){a=a.__extend__;this.VERSION=a.VERSION;this.AUTHORITY=a.AUTHORITY;delete a.VERSION;delete a.AUTHORITY;this.c=this.extractConstructor(a);this.adaptConstructor(this.c);
a.constructorOnly?delete a.constructorOnly:this.construct(a)},construct:function(a){if(this.prepareProps(a))this.processSuperClass(this.superClass=this.extractSuperClass(a)),this.adaptPrototype(this.c.prototype),this.finalize(a)},finalize:function(a){this.processStem(a);this.extend(a)},prepareProps:function(){return!0},extractConstructor:function(a){var c=a.hasOwnProperty("constructor")?a.constructor:this.defaultConstructor();delete a.constructor;return c},extractSuperClass:function(a){if(a.hasOwnProperty("isa")&&
!a.isa)throw Error("Attempt to inherit from undefined superclass ["+this.name+"]");var c=a.isa||this.defaultSuperClass;delete a.isa;return c},processStem:function(){var a=this.superClass.meta;this.methods=Joose.O.getMutableCopy(a.methods||{});this.attributes=Joose.O.getMutableCopy(a.attributes||{})},initInstance:function(a,c){Joose.O.copyOwn(c,a)},defaultConstructor:function(){return function(a){var c=this.BUILD,c=c&&c.apply(this,arguments)||a||{},d=this.meta;d.initInstance(this,c);return d.hasMethod("initialize")&&
this.initialize(c)||this}},processSuperClass:function(a){var c=a.prototype;if(!a.meta){var d=Joose.O.copy(c);d.isa=Joose.Proto.Empty;delete d.constructor;d=new this.defaultSuperClass.meta.constructor(null,d);a.meta=c.meta=d;d.c=a}this.c.prototype=Joose.O.getMutableCopy(c);this.c.superClass=c},adaptConstructor:function(a){a.meta=this;if(!a.hasOwnProperty("toString"))a.toString=function(){return this.meta.name}},adaptPrototype:function(a){a.constructor=this.c;a.meta=this},addMethod:function(a,c){c.SUPER=
this.superClass.prototype;c.methodName=a;this.methods[a]=c;this.c.prototype[a]=c},addAttribute:function(a,c){this.attributes[a]=c;this.c.prototype[a]=c},removeMethod:function(a){delete this.methods[a];delete this.c.prototype[a]},removeAttribute:function(a){delete this.attributes[a];delete this.c.prototype[a]},hasMethod:function(a){return Boolean(this.methods[a])},hasAttribute:function(a){return this.attributes[a]!==void 0},hasOwnMethod:function(a){return this.hasMethod(a)&&this.methods.hasOwnProperty(a)},
hasOwnAttribute:function(a){return this.hasAttribute(a)&&this.attributes.hasOwnProperty(a)},extend:function(a){Joose.O.eachOwn(a,function(a,b){b!="meta"&&b!="constructor"&&(Joose.O.isFunction(a)&&!a.meta?this.addMethod(b,a):this.addAttribute(b,a))},this)},subClassOf:function(a,c){return this.subClass(c,null,a)},subClass:function(a,c,d){a=a||{};a.isa=d||this.c;return(new this.constructor(c,a)).c},instantiate:function(){var a=function(){};a.prototype=this.c.prototype;a=new a;return this.c.apply(a,arguments)||
a}};Joose.Proto.Class.prototype=Joose.O.getMutableCopy(Joose.Proto.Object.prototype);Joose.O.extend(Joose.Proto.Class.prototype,a);Joose.Proto.Class.prototype.meta=new Joose.Proto.Class("Joose.Proto.Class",a);Joose.Proto.Class.meta.addMethod("isa",function(a){var c=function(){};c.prototype=this.c.prototype;return new c instanceof a})})();Joose.Managed=Joose.stub();
Joose.Managed.Property=(new Joose.Proto.Class("Joose.Managed.Property",{name:null,init:null,value:null,definedIn:null,initialize:function(a){Joose.Managed.Property.superClass.initialize.call(this,a);this.computeValue()},computeValue:function(){this.value=this.init},preApply:function(){},postUnApply:function(){},apply:function(a){a[this.name]=this.value},isAppliedTo:function(a){return a[this.name]==this.value},unapply:function(a){if(!this.isAppliedTo(a))throw"Unapply of property ["+this.name+"] from ["+
a+"] failed";delete a[this.name]},cloneProps:function(){return{name:this.name,init:this.init,definedIn:this.definedIn}},clone:function(a){var b=this.cloneProps();b.name=a||b.name;return new this.constructor(b)}})).c;Joose.Managed.Property.ConflictMarker=(new Joose.Proto.Class("Joose.Managed.Property.ConflictMarker",{isa:Joose.Managed.Property,apply:function(a){throw Error("Attempt to apply ConflictMarker ["+this.name+"] to ["+a+"]");}})).c;
Joose.Managed.Property.Requirement=(new Joose.Proto.Class("Joose.Managed.Property.Requirement",{isa:Joose.Managed.Property,apply:function(a){if(!a.meta.hasMethod(this.name))throw Error("Requirement ["+this.name+"], defined in ["+this.definedIn.definedIn.name+"] is not satisfied for class ["+a+"]");},unapply:function(){}})).c;
Joose.Managed.Property.Attribute=(new Joose.Proto.Class("Joose.Managed.Property.Attribute",{isa:Joose.Managed.Property,slot:null,initialize:function(){Joose.Managed.Property.Attribute.superClass.initialize.apply(this,arguments);this.slot=this.name},apply:function(a){a.prototype[this.slot]=this.value},isAppliedTo:function(a){return a.prototype[this.slot]==this.value},unapply:function(a){if(!this.isAppliedTo(a))throw"Unapply of property ["+this.name+"] from ["+a+"] failed";delete a.prototype[this.slot]},
clearValue:function(a){delete a[this.slot]},hasValue:function(a){return a.hasOwnProperty(this.slot)},getRawValueFrom:function(a){return a[this.slot]},setRawValueTo:function(a,b){a[this.slot]=b;return this}})).c;
Joose.Managed.Property.MethodModifier=(new Joose.Proto.Class("Joose.Managed.Property.MethodModifier",{isa:Joose.Managed.Property,prepareWrapper:function(){throw"Abstract method [prepareWrapper] of "+this+" was called";},apply:function(a){var b=this.name,c=a.prototype,d=c.hasOwnProperty(b),e=c[b],f=a.meta.superClass.prototype,a=this.prepareWrapper({name:b,modifier:this.value,isOwn:d,originalCall:d?e:function(){return f[b].apply(this,arguments)},superProto:f,target:a});if(d)a.__ORIGINAL__=e;a.__CONTAIN__=
this.value;a.__METHOD__=this;c[b]=a},isAppliedTo:function(a){return(a=a.prototype[this.name])&&a.__CONTAIN__==this.value},unapply:function(a){var b=this.name,c=a.prototype,d=c[b].__ORIGINAL__;if(!this.isAppliedTo(a))throw"Unapply of method ["+b+"] from class ["+a+"] failed";d?c[b]=d:delete c[b]}})).c;
Joose.Managed.Property.MethodModifier.Override=(new Joose.Proto.Class("Joose.Managed.Property.MethodModifier.Override",{isa:Joose.Managed.Property.MethodModifier,prepareWrapper:function(a){var b=a.modifier,c=a.originalCall,d=a.superProto,e=d.meta.constructor,f=c;(e==Joose.Proto.Class||e==Joose.Proto.Object)&&(!a.isOwn||!c.IS_OVERRIDE)&&(f=function(){var a=this.SUPER;this.SUPER=d.SUPER;var b=c.apply(this,arguments);this.SUPER=a;return b});a=function(){var a=this.SUPER;this.SUPER=f;var c=b.apply(this,
arguments);this.SUPER=a;return c};a.IS_OVERRIDE=!0;return a}})).c;Joose.Managed.Property.MethodModifier.Put=(new Joose.Proto.Class("Joose.Managed.Property.MethodModifier.Put",{isa:Joose.Managed.Property.MethodModifier.Override,prepareWrapper:function(a){if(a.isOwn)throw"Method ["+a.name+"] is applying over something ["+a.originalCall+"] in class ["+a.target+"]";return Joose.Managed.Property.MethodModifier.Put.superClass.prepareWrapper.call(this,a)}})).c;
Joose.Managed.Property.MethodModifier.After=(new Joose.Proto.Class("Joose.Managed.Property.MethodModifier.After",{isa:Joose.Managed.Property.MethodModifier,prepareWrapper:function(a){var b=a.modifier,c=a.originalCall;return function(){var a=c.apply(this,arguments);b.apply(this,arguments);return a}}})).c;
Joose.Managed.Property.MethodModifier.Before=(new Joose.Proto.Class("Joose.Managed.Property.MethodModifier.Before",{isa:Joose.Managed.Property.MethodModifier,prepareWrapper:function(a){var b=a.modifier,c=a.originalCall;return function(){b.apply(this,arguments);return c.apply(this,arguments)}}})).c;
Joose.Managed.Property.MethodModifier.Around=(new Joose.Proto.Class("Joose.Managed.Property.MethodModifier.Around",{isa:Joose.Managed.Property.MethodModifier,prepareWrapper:function(a){var b=a.modifier,c=a.originalCall,d,e=function(){return c.apply(d,arguments)};return function(){d=this;var a=[e];a.push.apply(a,arguments);return b.apply(this,a)}}})).c;
Joose.Managed.Property.MethodModifier.Augment=(new Joose.Proto.Class("Joose.Managed.Property.MethodModifier.Augment",{isa:Joose.Managed.Property.MethodModifier,prepareWrapper:function(a){var b=function(){var a=[],d=b;do a.push(d.IS_AUGMENT?d.__CONTAIN__:d),d=d.IS_AUGMENT&&(d.__ORIGINAL__||d.SUPER[d.methodName]);while(d);d=this.INNER;this.INNER=function(){var b=a.pop();return b?b.apply(this,arguments):void 0};var e=this.INNER.apply(this,arguments);this.INNER=d;return e};b.methodName=a.name;b.SUPER=
a.superProto;b.IS_AUGMENT=!0;return b}})).c;
Joose.Managed.PropertySet=(new Joose.Proto.Class("Joose.Managed.PropertySet",{isa:Joose.Managed.Property,properties:null,propertyMetaClass:Joose.Managed.Property,initialize:function(a){Joose.Managed.PropertySet.superClass.initialize.call(this,a);this.properties=a.properties||{}},addProperty:function(a,b){var c=b.meta||this.propertyMetaClass;delete b.meta;b.definedIn=this;b.name=a;return this.properties[a]=new c(b)},addPropertyObject:function(a){return this.properties[a.name]=a},removeProperty:function(a){var b=
this.properties[a];delete this.properties[a];return b},haveProperty:function(a){return this.properties[a]!=null},haveOwnProperty:function(a){return this.haveProperty(a)&&this.properties.hasOwnProperty(a)},getProperty:function(a){return this.properties[a]},each:function(a,b){Joose.O.each(this.properties,a,b||this)},eachOwn:function(a,b){Joose.O.eachOwn(this.properties,a,b||this)},eachAll:function(a,b){this.each(a,b)},cloneProps:function(){var a=Joose.Managed.PropertySet.superClass.cloneProps.call(this);
a.propertyMetaClass=this.propertyMetaClass;return a},clone:function(a){a=this.cleanClone(a);a.properties=Joose.O.copyOwn(this.properties);return a},cleanClone:function(a){var b=this.cloneProps();b.name=a||b.name;return new this.constructor(b)},alias:function(a){var b=this.properties;Joose.O.each(a,function(a,d){var e=b[d];e&&this.addPropertyObject(e.clone(a))},this)},exclude:function(a){var b=this.properties;Joose.A.each(a,function(a){delete b[a]})},beforeConsumedBy:function(){},flattenTo:function(a){var b=
a.properties;this.eachOwn(function(c,d){var e=b[d];e instanceof Joose.Managed.Property.ConflictMarker||(e==null?a.addPropertyObject(c):e!=c&&(a.removeProperty(d),a.addProperty(d,{meta:Joose.Managed.Property.ConflictMarker})))},this)},composeTo:function(a){this.eachOwn(function(b,c){a.haveOwnProperty(c)||a.addPropertyObject(b)})},composeFrom:function(){if(arguments.length){var a=this.cleanClone();Joose.A.each(arguments,function(b){var c=!(b instanceof Joose.Managed.PropertySet),d=c?b.propertySet:b;
d.beforeConsumedBy(this,a);if(c){if(b.alias||b.exclude)d=d.clone();b.alias&&d.alias(b.alias);b.exclude&&d.exclude(b.exclude)}d.flattenTo(a)},this);a.composeTo(this)}},preApply:function(a){this.eachOwn(function(b){b.preApply(a)})},apply:function(a){this.eachOwn(function(b){b.apply(a)})},unapply:function(a){this.eachOwn(function(b){b.unapply(a)})},postUnApply:function(a){this.eachOwn(function(b){b.postUnApply(a)})}})).c;
(function(){var a=1;Joose.Managed.PropertySet.Mutable=(new Joose.Proto.Class("Joose.Managed.PropertySet.Mutable",{isa:Joose.Managed.PropertySet,ID:null,derivatives:null,opened:null,composedFrom:null,initialize:function(b){Joose.Managed.PropertySet.Mutable.superClass.initialize.call(this,b);this.opened=1;this.derivatives={};this.ID=a++;this.composedFrom=[]},addComposeInfo:function(){this.ensureOpen();Joose.A.each(arguments,function(a){this.composedFrom.push(a);(a instanceof Joose.Managed.PropertySet?
a:a.propertySet).derivatives[this.ID]=this},this)},removeComposeInfo:function(){this.ensureOpen();Joose.A.each(arguments,function(a){for(var c=0;c<this.composedFrom.length;){var d=this.composedFrom[c],d=d instanceof Joose.Managed.PropertySet?d:d.propertySet;a==d?(delete d.derivatives[this.ID],this.composedFrom.splice(c,1)):c++}},this)},ensureOpen:function(){if(!this.opened)throw"Mutation of closed property set: ["+this.name+"]";},addProperty:function(a,c){this.ensureOpen();return Joose.Managed.PropertySet.Mutable.superClass.addProperty.call(this,
a,c)},addPropertyObject:function(a){this.ensureOpen();return Joose.Managed.PropertySet.Mutable.superClass.addPropertyObject.call(this,a)},removeProperty:function(a){this.ensureOpen();return Joose.Managed.PropertySet.Mutable.superClass.removeProperty.call(this,a)},composeFrom:function(){this.ensureOpen();return Joose.Managed.PropertySet.Mutable.superClass.composeFrom.apply(this,this.composedFrom)},open:function(){this.opened++;this.opened==1&&(Joose.O.each(this.derivatives,function(a){a.open()}),this.deCompose())},
close:function(){if(!this.opened)throw"Unmatched 'close' operation on property set: ["+this.name+"]";this.opened==1&&(this.reCompose(),Joose.O.each(this.derivatives,function(a){a.close()}));this.opened--},reCompose:function(){this.composeFrom()},deCompose:function(){this.eachOwn(function(a,c){a.definedIn!=this&&this.removeProperty(c)},this)}})).c})();Joose.Managed.StemElement=function(){throw"Modules may not be instantiated.";};
Joose.Managed.StemElement.Attributes=(new Joose.Proto.Class("Joose.Managed.StemElement.Attributes",{isa:Joose.Managed.PropertySet.Mutable,propertyMetaClass:Joose.Managed.Property.Attribute})).c;Joose.Managed.StemElement.Methods=(new Joose.Proto.Class("Joose.Managed.StemElement.Methods",{isa:Joose.Managed.PropertySet.Mutable,propertyMetaClass:Joose.Managed.Property.MethodModifier.Put,preApply:function(){},postUnApply:function(){}})).c;
Joose.Managed.StemElement.Requirements=(new Joose.Proto.Class("Joose.Managed.StemElement.Requirements",{isa:Joose.Managed.PropertySet.Mutable,propertyMetaClass:Joose.Managed.Property.Requirement,alias:function(){},exclude:function(){},flattenTo:function(a){this.each(function(b,c){a.haveProperty(c)||a.addPropertyObject(b)})},composeTo:function(a){this.flattenTo(a)},preApply:function(){},postUnApply:function(){}})).c;
Joose.Managed.StemElement.MethodModifiers=(new Joose.Proto.Class("Joose.Managed.StemElement.MethodModifiers",{isa:Joose.Managed.PropertySet.Mutable,propertyMetaClass:null,addProperty:function(a,b){var c=b.meta;delete b.meta;b.definedIn=this;b.name=a;var c=new c(b),d=this.properties;d[a]||(d[a]=[]);d[a].push(c);return c},addPropertyObject:function(a){var b=a.name,c=this.properties;c[b]||(c[b]=[]);c[b].push(a);return a},removeProperty:function(a){if(this.haveProperty(a)){var b=this.properties,c=b[a].pop();
b[a].length||Joose.Managed.StemElement.MethodModifiers.superClass.removeProperty.call(this,a);return c}},alias:function(){},exclude:function(){},flattenTo:function(a){var b=a.properties;this.each(function(a,d){var e=b[d];e==null&&(e=b[d]=[]);Joose.A.each(a,function(a){Joose.A.exists(e,a)||e.push(a)})})},composeTo:function(a){this.flattenTo(a)},deCompose:function(){this.each(function(a){for(var b=0;b<a.length;)a[b].definedIn!=this?a.splice(b,1):b++})},preApply:function(){},postUnApply:function(){},
apply:function(a){this.each(function(b){Joose.A.each(b,function(b){b.apply(a)})})},unapply:function(a){this.each(function(b){for(var c=b.length-1;c>=0;c--)b[c].unapply(a)})}})).c;
Joose.Managed.PropertySet.Composition=(new Joose.Proto.Class("Joose.Managed.PropertySet.Composition",{isa:Joose.Managed.PropertySet.Mutable,propertyMetaClass:Joose.Managed.PropertySet.Mutable,processOrder:null,each:function(a,b){var c=this.properties,b=b||this;Joose.A.each(this.processOrder,function(d){a.call(b,c[d],d)})},eachR:function(a,b){var c=this.properties,b=b||this;Joose.A.eachR(this.processOrder,function(d){a.call(b,c[d],d)})},clone:function(a){var b=this.cleanClone(a);this.each(function(a){b.addPropertyObject(a.clone())});
return b},alias:function(a){this.each(function(b){b.alias(a)})},exclude:function(a){this.each(function(b){b.exclude(a)})},flattenTo:function(a){var b=a.properties;this.each(function(c,d){var e=b[d]||a.addProperty(d,{meta:c.constructor});c.flattenTo(e)})},composeTo:function(a){var b=a.properties;this.each(function(c,d){var e=b[d]||a.addProperty(d,{meta:c.constructor});c.composeTo(e)})},deCompose:function(){this.eachR(function(a){a.open()});Joose.Managed.PropertySet.Composition.superClass.deCompose.call(this)},
reCompose:function(){Joose.Managed.PropertySet.Composition.superClass.reCompose.call(this);this.each(function(a){a.close()})},unapply:function(a){this.eachR(function(b){b.unapply(a)})}})).c;
Joose.Managed.Stem=(new Joose.Proto.Class("Joose.Managed.Stem",{isa:Joose.Managed.PropertySet.Composition,targetMeta:null,attributesMC:Joose.Managed.StemElement.Attributes,methodsMC:Joose.Managed.StemElement.Methods,requirementsMC:Joose.Managed.StemElement.Requirements,methodsModifiersMC:Joose.Managed.StemElement.MethodModifiers,processOrder:["attributes","methods","requirements","methodsModifiers"],initialize:function(a){Joose.Managed.Stem.superClass.initialize.call(this,a);a=this.targetMeta;this.addProperty("attributes",
{meta:this.attributesMC,properties:a?a.attributes:{}});this.addProperty("methods",{meta:this.methodsMC,properties:a?a.methods:{}});this.addProperty("requirements",{meta:this.requirementsMC});this.addProperty("methodsModifiers",{meta:this.methodsModifiersMC})},reCompose:function(){var a=this.targetMeta.c;this.preApply(a);Joose.Managed.Stem.superClass.reCompose.call(this);this.apply(a)},deCompose:function(){var a=this.targetMeta.c;this.unapply(a);Joose.Managed.Stem.superClass.deCompose.call(this);this.postUnApply(a)}})).c;
Joose.Managed.Builder=(new Joose.Proto.Class("Joose.Managed.Builder",{targetMeta:null,_buildStart:function(a,b){a.stem.open();Joose.A.each(["trait","traits","removeTrait","removeTraits","does","doesnot","doesnt"],function(c){b[c]&&(this[c](a,b[c]),delete b[c])},this)},_extend:function(a){if(!Joose.O.isEmpty(a)){var b=this.targetMeta;this._buildStart(b,a);Joose.O.eachOwn(a,function(a,d){var e=this[d];if(!e)throw Error("Unknown builder ["+d+"] was used during extending of ["+b.c+"]");e.call(this,b,
a)},this);this._buildComplete(b,a)}},_buildComplete:function(a){a.stem.close()},methods:function(a,b){Joose.O.eachOwn(b,function(b,d){a.addMethod(d,b)})},removeMethods:function(a,b){Joose.A.each(b,function(b){a.removeMethod(b)})},have:function(a,b){Joose.O.eachOwn(b,function(b,d){a.addAttribute(d,b)})},havenot:function(a,b){Joose.A.each(b,function(b){a.removeAttribute(b)})},havent:function(a,b){this.havenot(a,b)},after:function(a,b){Joose.O.each(b,function(b,d){a.addMethodModifier(d,b,Joose.Managed.Property.MethodModifier.After)})},
before:function(a,b){Joose.O.each(b,function(b,d){a.addMethodModifier(d,b,Joose.Managed.Property.MethodModifier.Before)})},override:function(a,b){Joose.O.each(b,function(b,d){a.addMethodModifier(d,b,Joose.Managed.Property.MethodModifier.Override)})},around:function(a,b){Joose.O.each(b,function(b,d){a.addMethodModifier(d,b,Joose.Managed.Property.MethodModifier.Around)})},augment:function(a,b){Joose.O.each(b,function(b,d){a.addMethodModifier(d,b,Joose.Managed.Property.MethodModifier.Augment)})},removeModifier:function(a,
b){Joose.A.each(b,function(b){a.removeMethodModifier(b)})},does:function(a,b){Joose.A.each(Joose.O.wantArray(b),function(b){a.addRole(b)})},doesnot:function(a,b){Joose.A.each(Joose.O.wantArray(b),function(b){a.removeRole(b)})},doesnt:function(a,b){this.doesnot(a,b)},trait:function(){this.traits.apply(this,arguments)},traits:function(a,b){if(!a.firstPass){if(!a.meta.isDetached)throw"Can't apply trait to not detached class";a.meta.extend({does:b})}},removeTrait:function(){this.removeTraits.apply(this,
arguments)},removeTraits:function(a,b){if(!a.meta.isDetached)throw"Can't remove trait from not detached class";a.meta.extend({doesnot:b})}})).c;
Joose.Managed.Class=(new Joose.Proto.Class("Joose.Managed.Class",{isa:Joose.Proto.Class,stem:null,stemClass:Joose.Managed.Stem,stemClassCreated:!1,builder:null,builderClass:Joose.Managed.Builder,builderClassCreated:!1,isDetached:!1,firstPass:!0,skipTraitsAnchor:{},BUILD:function(){var a=Joose.Managed.Class.superClass.BUILD.apply(this,arguments),b=a.__extend__,c=Joose.O.wantArray(b.trait||b.traits||[]);delete b.trait;delete b.traits;Joose.A.each(Joose.O.wantArray(b.does||[]),function(a){a=a.meta instanceof
Joose.Managed.Class?a:a.role;a.meta.meta.isDetached&&c.push(a.meta.constructor)});if(c.length)b.traits=c;return a},initInstance:function(a,b){Joose.O.each(this.attributes,function(c,d){c instanceof Joose.Managed.Attribute?c.initFromConfig(a,b):b.hasOwnProperty(d)&&(a[d]=b[d])})},defaultConstructor:function(){return function(a,b){var c=this.meta,d=a==c.skipTraitsAnchor,e=this.BUILD,e=e&&e.apply(this,d?b:arguments)||(d?b[0]:a)||{},f=e.__extend__||e,i=f.trait||f.traits;if(i||f.detached)if(delete f.trait,
delete f.traits,delete f.detached,!d)return d=c.subClass({does:i||[]},c.name).meta,d.isDetached=!0,d.instantiate(c.skipTraitsAnchor,arguments);c.initInstance(this,e);return c.hasMethod("initialize")&&this.initialize(e)||this}},finalize:function(a){Joose.Managed.Class.superClass.finalize.call(this,a);this.stem.close();this.afterMutate()},processStem:function(){Joose.Managed.Class.superClass.processStem.call(this);this.builder=new this.builderClass({targetMeta:this});this.stem=new this.stemClass({name:this.name,
targetMeta:this});var a=this.getClassInAttribute("builderClass");if(a)this.builderClassCreated=!0,this.addAttribute("builderClass",this.subClassOf(a));if(a=this.getClassInAttribute("stemClass"))this.stemClassCreated=!0,this.addAttribute("stemClass",this.subClassOf(a))},extend:function(a){a.builder&&(this.getBuilderTarget().meta.extend(a.builder),delete a.builder);a.stem&&(this.getStemTarget().meta.extend(a.stem),delete a.stem);this.builder._extend(a);this.firstPass=!1;this.stem.opened||this.afterMutate()},
getBuilderTarget:function(){var a=this.getClassInAttribute("builderClass");if(!a)throw"Attempt to extend a builder on non-meta class";return a},getStemTarget:function(){var a=this.getClassInAttribute("stemClass");if(!a)throw"Attempt to extend a stem on non-meta class";return a},getClassInAttribute:function(a){a=this.getAttribute(a);if(a instanceof Joose.Managed.Property.Attribute)a=a.value;return a},addMethodModifier:function(a,b,c){var d={};d.init=b;d.meta=c;return this.stem.properties.methodsModifiers.addProperty(a,
d)},removeMethodModifier:function(a){return this.stem.properties.methodsModifiers.removeProperty(a)},addMethod:function(a,b,c){c=c||{};c.init=b;return this.stem.properties.methods.addProperty(a,c)},addAttribute:function(a,b,c){c=c||{};c.init=b;return this.stem.properties.attributes.addProperty(a,c)},removeMethod:function(a){return this.stem.properties.methods.removeProperty(a)},removeAttribute:function(a){return this.stem.properties.attributes.removeProperty(a)},hasMethod:function(a){return this.stem.properties.methods.haveProperty(a)},
hasAttribute:function(a){return this.stem.properties.attributes.haveProperty(a)},hasMethodModifiersFor:function(a){return this.stem.properties.methodsModifiers.haveProperty(a)},hasOwnMethod:function(a){return this.stem.properties.methods.haveOwnProperty(a)},hasOwnAttribute:function(a){return this.stem.properties.attributes.haveOwnProperty(a)},getMethod:function(a){return this.stem.properties.methods.getProperty(a)},getAttribute:function(a){return this.stem.properties.attributes.getProperty(a)},eachRole:function(a,
b,c){Joose.A.each(a,function(a,e){b.call(c||this,a,a.meta instanceof Joose.Managed.Class?a:a.role,e)},this)},addRole:function(){this.eachRole(arguments,function(a,b){this.beforeRoleAdd(b);var c=a;b!=a?(c.propertySet=b.meta.stem,delete c.role):c=c.meta.stem;this.stem.addComposeInfo(c)},this)},beforeRoleAdd:function(a){a=a.meta;a.builderClassCreated&&this.getBuilderTarget().meta.extend({does:[a.getBuilderTarget()]});a.stemClassCreated&&this.getStemTarget().meta.extend({does:[a.getStemTarget()]});a.meta.isDetached&&
!this.firstPass&&this.builder.traits(this,a.constructor)},beforeRoleRemove:function(a){a=a.meta;a.builderClassCreated&&this.getBuilderTarget().meta.extend({doesnt:[a.getBuilderTarget()]});a.stemClassCreated&&this.getStemTarget().meta.extend({doesnt:[a.getStemTarget()]});a.meta.isDetached&&!this.firstPass&&this.builder.removeTraits(this,a.constructor)},removeRole:function(){this.eachRole(arguments,function(a,b){this.beforeRoleRemove(b);this.stem.removeComposeInfo(b.meta.stem)},this)},getRoles:function(){return Joose.A.map(this.stem.composedFrom,
function(a){if(!(a instanceof Joose.Managed.PropertySet))return a.propertySet;return a.targetMeta.c})},does:function(a){for(var b=this.getRoles(),c=0;c<b.length;c++)if(a==b[c])return!0;for(c=0;c<b.length;c++)if(b[c].meta.does(a))return!0;b=this.superClass.meta;if(this.superClass!=Joose.Proto.Empty&&b&&b.meta&&b.meta.hasMethod("does"))return b.does(a);return!1},getMethods:function(){return this.stem.properties.methods},getAttributes:function(){return this.stem.properties.attributes},afterMutate:function(){},
getCurrentMethod:function(){for(var a=arguments.callee.caller,b=0;a&&b<5;a=a.caller,b++)if(a.__METHOD__)return a.__METHOD__;return null}})).c;
Joose.Managed.Role=(new Joose.Managed.Class("Joose.Managed.Role",{isa:Joose.Managed.Class,have:{defaultSuperClass:Joose.Proto.Empty,builderRole:null,stemRole:null},methods:{defaultConstructor:function(){return function(){throw Error("Roles cant be instantiated");}},processSuperClass:function(){if(this.superClass!=this.defaultSuperClass)throw Error("Roles can't inherit from anything");},getBuilderTarget:function(){if(!this.builderRole)this.builderRole=(new this.constructor).c,this.builderClassCreated=
!0;return this.builderRole},getStemTarget:function(){if(!this.stemRole)this.stemRole=(new this.constructor).c,this.stemClassCreated=!0;return this.stemRole},addRequirement:function(a){this.stem.properties.requirements.addProperty(a,{})}},stem:{methods:{apply:function(){},unapply:function(){}}},builder:{methods:{requires:function(a,b){Joose.A.each(Joose.O.wantArray(b),function(b){a.addRequirement(b)},this)}}}})).c;
Joose.Managed.Attribute=(new Joose.Managed.Class("Joose.Managed.Attribute",{isa:Joose.Managed.Property.Attribute,have:{is:null,builder:null,isPrivate:!1,role:null,publicName:null,setterName:null,getterName:null,readable:!1,writeable:!1,hasGetter:!1,hasSetter:!1,required:!1,canInlineSetRaw:!0,canInlineGetRaw:!0},after:{initialize:function(){var a=this.name;this.publicName=a.replace(/^_+/,"");this.slot=this.isPrivate?"$$"+a:a;this.setterName=this.setterName||this.getSetterName();this.getterName=this.getterName||
this.getGetterName();this.readable=this.hasGetter=/^r/i.test(this.is);this.writeable=this.hasSetter=/^.w/i.test(this.is)}},override:{computeValue:function(){Joose.O.isFunction(this.init)||this.SUPER()},preApply:function(a){a.meta.extend({methods:this.getAccessorsFor(a)})},postUnApply:function(a){a.meta.extend({removeMethods:this.getAccessorsFrom(a)})}},methods:{getAccessorsFor:function(a){var a=a.meta,b=this.setterName,c=this.getterName,d={};if(this.hasSetter&&!a.hasMethod(b))d[b]=this.getSetter(),
d[b].ACCESSOR_FROM=this;if(this.hasGetter&&!a.hasMethod(c))d[c]=this.getGetter(),d[c].ACCESSOR_FROM=this;return d},getAccessorsFrom:function(a){var b=a.meta,a=this.setterName,c=this.getterName,d=this.hasSetter&&b.getMethod(a),b=this.hasGetter&&b.getMethod(c),e=[];d&&d.value.ACCESSOR_FROM==this&&e.push(a);b&&b.value.ACCESSOR_FROM==this&&e.push(c);return e},getGetterName:function(){return"get"+Joose.S.uppercaseFirst(this.publicName)},getSetterName:function(){return"set"+Joose.S.uppercaseFirst(this.publicName)},
getSetter:function(){var a=this,b=a.slot;return a.canInlineSetRaw?function(a){this[b]=a;return this}:function(){return a.setRawValueTo.apply(this,arguments)}},getGetter:function(){var a=this,b=a.slot;return a.canInlineGetRaw?function(){return this[b]}:function(){return a.getRawValueFrom.apply(this,arguments)}},getValueFrom:function(a){var b=this.getterName;if(this.readable&&a.meta.hasMethod(b))return a[b]();return this.getRawValueFrom(a)},setValueTo:function(a,b){var c=this.setterName;if(this.writeable&&
a.meta.hasMethod(c))a[c](b);else this.setRawValueTo(a,b)},initFromConfig:function(a,b){var c=this.name,d,e=!1;b.hasOwnProperty(c)?(d=b[c],e=!0):Joose.O.isFunction(this.init)?(d=this.init.call(a,b,c),e=!0):this.builder&&(d=a[this.builder.replace(/^this\./,"")](b,c),e=!0);if(e)this.setRawValueTo(a,d);else if(this.required)throw Error("Required attribute ["+c+"] is missed during initialization of "+a);}}})).c;
Joose.Managed.PropertySet.Namespace=(new Joose.Proto.Class("Joose.Managed.PropertySet.Namespace",{isa:Joose.Managed.PropertySet,propertyMetaClass:null,targetMeta:null,container:null,initialize:function(a){Joose.Managed.PropertySet.Namespace.superClass.initialize.call(this,a);this.container=this.targetMeta.c},addProperty:function(a,b){if(b&&b.meta&&b.meta.meta.hasAttribute("ns"))b.meta.parentNs=this.targetMeta.ns;return this.container[a]=this.properties[a]=b},removeProperty:function(a){try{delete this.container[a]}catch(b){this.container[a]=
void 0}return Joose.Managed.PropertySet.Namespace.superClass.removeProperty.call(this,a)}})).c;
Joose.Managed.Attribute.Builder=(new Joose.Managed.Role("Joose.Managed.Attribute.Builder",{have:{defaultAttributeClass:Joose.Managed.Attribute},builder:{methods:{has:function(a,b){Joose.O.eachOwn(b,function(b,d){if(typeof b!="object"||b==null||b.constructor==/ /.constructor)b={init:b};b.meta=b.meta||a.defaultAttributeClass;if(/^__/.test(d))d=d.replace(/^_+/,""),b.isPrivate=!0;a.addAttribute(d,b.init,b)},this)},hasnot:function(a,b){this.havenot(a,b)},hasnt:function(a,b){this.hasnot(a,b)}}}})).c;
Joose.Managed.My=(new Joose.Managed.Role("Joose.Managed.My",{have:{myClass:null,needToReAlias:!1},methods:{createMy:function(a){var b=this instanceof Joose.Managed.Role,c=a.my||{};delete a.my;a=this.superClass.meta.myClass;if(!b&&!c.isa&&a)c.isa=a;if(!c.meta&&!c.isa)c.meta=this.constructor;c=this.myClass=Class(c);a=this.c;a.prototype.my=a.my=b?c:new c({HOST:a});this.needToReAlias=!0},aliasStaticMethods:function(){this.needToReAlias=!1;var a=this.c,b=this.myClass.prototype;Joose.O.eachOwn(a,function(b,
d){b.IS_ALIAS&&delete a[d]});this.myClass.meta.stem.properties.methods.each(function(c,d){if(!a[d])(a[d]=function(){return b[d].apply(a.my,arguments)}).IS_ALIAS=!0})}},override:{extend:function(a){var b=this.myClass;!b&&this.superClass.meta.myClass&&this.createMy(a);if(a.my)b?(this.needToReAlias=!0,b.meta.extend(a.my),delete a.my):this.createMy(a);this.SUPER(a);this.needToReAlias&&!(this instanceof Joose.Managed.Role)&&this.aliasStaticMethods()}},before:{addRole:function(){var a;Joose.A.each(arguments,
function(b){if(!b)throw Error("Attempt to consume an undefined Role into ["+this.name+"]");b=b.meta instanceof Joose.Managed.Class?b:b.role;if(b.meta.meta.hasAttribute("myClass")&&b.meta.myClass)this.myClass?(a=this.myClass.meta.stem,a.opened||a.open(),a.addComposeInfo(b.my.meta.stem)):this.createMy({my:{does:b.meta.myClass}})},this);if(a)a.close(),this.needToReAlias=!0},removeRole:function(){if(this.myClass){var a=this.myClass.meta.stem;a.open();Joose.A.each(arguments,function(b){if(b.meta.meta.hasAttribute("myClass")&&
b.meta.myClass)a.removeComposeInfo(b.my.meta.stem),this.needToReAlias=!0},this);a.close()}}}})).c;Joose.Namespace=Joose.stub();
Joose.Namespace.Able=(new Joose.Managed.Role("Joose.Namespace.Able",{have:{parentNs:null,ns:null,bodyFunc:null},before:{extend:function(a){if(a.body)this.bodyFunc=a.body,delete a.body}},after:{adaptConstructor:function(){var a=(this.name||"").split(".").pop();this.ns=new Joose.Managed.PropertySet.Namespace({name:a,targetMeta:this})},afterMutate:function(){var a=this.bodyFunc;delete this.bodyFunc;a&&Joose.Namespace.Manager.my.executeIn(this.c,a)}}})).c;
Joose.Managed.Bootstrap=(new Joose.Managed.Role("Joose.Managed.Bootstrap",{does:[Joose.Namespace.Able,Joose.Managed.My,Joose.Managed.Attribute.Builder]})).c;Joose.Meta=Joose.stub();Joose.Meta.Object=(new Joose.Proto.Class("Joose.Meta.Object",{isa:Joose.Proto.Object})).c;Joose.Meta.Class=(new Joose.Managed.Class("Joose.Meta.Class",{isa:Joose.Managed.Class,does:Joose.Managed.Bootstrap,have:{defaultSuperClass:Joose.Meta.Object}})).c;
Joose.Meta.Role=(new Joose.Meta.Class("Joose.Meta.Role",{isa:Joose.Managed.Role,does:Joose.Managed.Bootstrap})).c;
Joose.Namespace.Keeper=(new Joose.Meta.Class("Joose.Namespace.Keeper",{isa:Joose.Meta.Class,have:{externalConstructor:null},methods:{defaultConstructor:function(){return function(){var a=arguments.callee.meta;if(a instanceof Joose.Namespace.Keeper)throw Error("Module ["+a.c+"] may not be instantiated. Forgot to 'use' the class with the same name?");var b=a.externalConstructor;if(typeof b=="function")return b.meta=a,b.apply(this,arguments);throw"NamespaceKeeper of ["+a.name+"] was planted incorrectly.";
}},plant:function(a){this.copyNamespaceState(a);var b=this.c;b.meta=a.meta;b.meta.c=b;b.meta.externalConstructor=a},copyNamespaceState:function(a){a=a.meta;a.parentNs=this.parentNs;a.ns=this.ns}}})).c;
Joose.Namespace.Manager=(new Joose.Managed.Class("Joose.Namespace.Manager",{have:{global:null,globalNs:null,current:null},methods:{initialize:function(){var a=this.global=(new Joose.Namespace.Keeper("")).c;(this.globalNs=a.meta.ns).container=Joose.is_NodeJS&&global||Joose.top;a.meta.parentNs=a;this.current=[a]},getCurrent:function(){return this.current[0]},executeIn:function(a,b){var c=this.current,d=a.meta.ns?a.meta.ns.container:a;c.unshift(a);d=b.call(d,a);c.shift();return d},earlyCreate:function(a,
b,c){c.constructorOnly=!0;return(new b(a,c)).c},create:function(a,b,c){if(!a)return(new b(a,c)).c;var d=this;if(/^\./.test(a))return this.executeIn(this.global,function(){return d.create(a.replace(/^\./,""),b,c)});props=c||{};for(var e=Joose.S.saneSplit(a,"."),f=this.getCurrent(),i=Joose.S.saneSplit(f.meta.name,"."),k=0;k<e.length;k++){var h=e[k],l=k==e.length-1;if(h=="meta"||h=="my"||!h)throw"Module name ["+a+"] may not include a part called 'meta' or 'my' or empty part.";var g=(f==this.global?this.global.meta.ns.container:
f)[h];i.push(h);var j=i.join("."),m=!1;if(typeof g=="undefined")l?(g=this.earlyCreate(j,b,props),m=!0):g=(new Joose.Namespace.Keeper(j)).c,f.meta?f.meta.ns.addProperty(h,g):f[h]=g;else if(l&&g&&g.meta)if(f=g.meta,b==Joose.Namespace.Keeper)f.extend(props);else if(f instanceof Joose.Namespace.Keeper)f.plant(this.earlyCreate(j,b,props)),m=!0;else throw Error("Double declaration of ["+j+"]");else if(l&&(!g||!g.meta||!g.meta.meta||!g.meta.meta.hasAttribute("ns")))throw"Trying to setup module "+j+" failed. There is already something: "+
g;m&&g.meta.construct(props);f=g}return f},prepareProperties:function(a,b,c,d){a&&typeof a!="string"&&(b=a,a=null);var e;if(b&&b.meta)e=b.meta,delete b.meta;e||(e=b&&typeof b.isa=="function"&&b.isa.meta?b.isa.meta.constructor:c);return d.call(this,a,e,b)},getDefaultHelperFor:function(a){var b=this;return function(c,d){return b.prepareProperties(c,d,a,function(a,c,d){return b.create(a,c,d)})}},register:function(a,b,c){var d=this;if(this.meta.hasMethod(a))b=function(){return d[a].apply(d,arguments)},
Joose.top[a]||(Joose.top[a]=b),Joose[a]||(Joose[a]=b),Joose.is_NodeJS&&!global[a]&&(global[a]=b);else{var e={};e[a]=c||this.getDefaultHelperFor(b);this.meta.extend({methods:e});this.register(a)}},Module:function(a,b){return this.prepareProperties(a,b,Joose.Namespace.Keeper,function(a,b,e){typeof e=="function"&&(e={body:e});return this.create(a,b,e)})}}})).c;Joose.Namespace.Manager.my=new Joose.Namespace.Manager;Joose.Namespace.Manager.my.register("Class",Joose.Meta.Class);
Joose.Namespace.Manager.my.register("Role",Joose.Meta.Role);Joose.Namespace.Manager.my.register("Module");
